/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class'],
  content: [
    './index.html',
    './src/**/*.{ts,tsx,js,jsx}',
  ],
  theme: {
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: '#3b7de8',
          foreground: '#ffffff',
        },
        accent: {
          DEFAULT: '#004ac6',
          foreground: '#ffffff',
        },
        highlight: {
          DEFAULT: '#9fbdf0',
          foreground: '#1a3a6b',
        },
        secondary: {
          DEFAULT: '#545f73',
          foreground: '#ffffff',
        },
        tertiary: '#784b00',
        error: '#ba1a1a',
        surface: 'hsl(var(--surface) / <alpha-value>)',
        'surface-dim': 'hsl(var(--surface-dim) / <alpha-value>)',
        'surface-bright': 'hsl(var(--surface-bright) / <alpha-value>)',
        'surface-container-lowest': 'hsl(var(--surface-container-lowest) / <alpha-value>)',
        'surface-container-low': 'hsl(var(--surface-container-low) / <alpha-value>)',
        'surface-container': 'hsl(var(--surface-container) / <alpha-value>)',
        'surface-container-high': 'hsl(var(--surface-container-high) / <alpha-value>)',
        'surface-container-highest': 'hsl(var(--surface-container-highest) / <alpha-value>)',
        'on-surface': 'hsl(var(--on-surface) / <alpha-value>)',
        'on-surface-variant': 'hsl(var(--on-surface-variant) / <alpha-value>)',
        'on-primary': '#ffffff',
        'on-secondary': '#ffffff',
        'on-tertiary': '#ffffff',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'primary-container': '#2563eb',
        'on-primary-container': '#eeefff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'success': '#18a34a',
        'on-success': '#ffffff',
        'success-container': '#dcfce7',
        'on-success-container': '#166534',
        'secondary-container': 'hsl(var(--secondary-container) / <alpha-value>)',
        'on-secondary-container': 'hsl(var(--on-secondary-container) / <alpha-value>)',
        'outline': 'hsl(var(--outline) / <alpha-value>)',
        'outline-variant': 'hsl(var(--outline-variant) / <alpha-value>)',
        'inverse-surface': 'hsl(var(--inverse-surface) / <alpha-value>)',
        'inverse-on-surface': 'hsl(var(--inverse-on-surface) / <alpha-value>)',
        'inverse-primary': 'hsl(var(--inverse-primary) / <alpha-value>)',
      },
      backgroundColor: {
        'glass-header': 'rgba(255, 255, 255, 0.8)',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
    },
  },
  plugins: [],
}
