/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class'],
  content: [
    './index.html',
    './src/**/*.{ts,tsx,js,jsx}',
  ],
  theme: {
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: '#004ac6',
          foreground: '#ffffff',
        },
        secondary: {
          DEFAULT: '#545f73',
          foreground: '#ffffff',
        },
        tertiary: '#784b00',
        error: '#ba1a1a',
        surface: '#f9f9ff',
        'surface-dim': '#cfdaf2',
        'surface-bright': '#f9f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f0f3ff',
        'surface-container': '#e7eeff',
        'surface-container-high': '#dee8ff',
        'surface-container-highest': '#d8e3fb',
        'on-surface': '#111c2d',
        'on-surface-variant': '#434655',
        'on-primary': '#ffffff',
        'on-secondary': '#ffffff',
        'on-tertiary': '#ffffff',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'primary-container': '#2563eb',
        'on-primary-container': '#eeefff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'success': '#18a34a',
        'on-success': '#ffffff',
        'success-container': '#dcfce7',
        'on-success-container': '#166534',
        'secondary-container': '#d5e0f8',
        'on-secondary-container': '#586377',
        'outline': '#737686',
        'outline-variant': '#c3c6d7',
        'inverse-surface': '#263143',
        'inverse-on-surface': '#ecf1ff',
        'inverse-primary': '#b4c5ff',
      },
      backgroundColor: {
        'glass-header': 'rgba(255, 255, 255, 0.8)',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
    },
  },
  plugins: [],
}
