services:
  db:
    image: postgres:16
    container_name: cinema_db
    environment:
      POSTGRES_DB: cinema_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  cache:
    image: redis:7
    container_name: cinema_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cinema_backend
    depends_on:
      - db
      - cache
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cinema_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "123"
      SPRING_DATA_REDIS_HOST: cache
      SPRING_DATA_REDIS_PORT: "6379"
      APP_JWT_SECRET: "U0VDUkVUX0tFWV9GT1JfQ0lORU1BX0JPT0tJTkdfU1lTVEVNX0RFVl9PTkxZXzMyQl9NSU4="
    ports:
      - "8080:8080"

volumes:
  db_data:
  redis_data:
