name: Run Tests

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'cinema-booking-system/frontend/**'
      - 'cinema-booking-system/backend-legacy/**'
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'cinema-booking-system/frontend/**'
      - 'cinema-booking-system/backend-legacy/**'
  workflow_dispatch:
jobs:
  changes:
    name: Detect File Changes
    runs-on: ubuntu-latest
    outputs:
      backend-legacy: ${{ steps.filter.outputs.backend-legacy }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend-legacy:
              - 'cinema-booking-system/backend-legacy/**'
            frontend:
              - 'cinema-booking-system/frontend/**'

  backend-tests:
    name: Backend unit tests
    needs: changes
    if: ${{ needs.changes.outputs.backend-legacy == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "maven"

      - name: Run backend tests
        working-directory: cinema-booking-system/backend-legacy
        run: mvn test